name: Ejecutar busca_archivo.sh

on:
  push:
    branches:
      - master

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Dar permisos de ejecución al script
        run: chmod +x busca_archivo.sh

      - name: Ejecutar script busca_archivo.sh
        run: ./busca_archivo.sh login.txt