name: Verificar archivo

on:
  push:
    paths:
      - 'verifica_archivo.sh'
      - '.github/workflows/verifica_archivo.yml'

jobs:
  run-verificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Dar permisos de ejecución al script
        run: chmod +x verifica_archivo.sh

      - name: Ejecutar script de verificación
        run: ./verifica_archivo.sh
